### ISSUE TITLE
Crash?

### ISSUE THREAD

**Issue by therealOri** [GillesVandewiele/Wordle-Bot#1]
Running the `wordle.py` file with a larger wordlist. 3b1b's 12k word list to be precise. Will make its way to 63% and then my computer freezes and then the terminal kills what's running and it stops.

```bash
(wdlENV) [ori@orio Wordle-Bot]$ python wordle.py

 63%|█████████████████████████████████████████████▋                          | 8226/12972 [04:43<07:08, 11.07it/s]
Killed

(wdlENV) [ori@orio Wordle-Bot]$ 
```

No idea as to why this happens but it does...

**Comment by GillesVandewiele** [comment]
How much RAM memory do you have? The code is not really optimized in terms of memory (or optimized in any terms at all), so after doing a quick run here on the word list of 3b1b, you might need around 10-12 gigs of memory.


A (slight) fix from the top of my head: the dictionary representation could be done much more efficiently. Currently we use 5 integers for every possible combination (and there are `3**5` or `243` of them). So roughly `250*5` integers, let's say 4 bytes each, which means 5000 bytes per word. Just replacing those 5 integers by a string of 5 characters requires only 1250 bytes and cuts down memory usage by 4 (i.e. `(0, 1, 2, 0, 1)` becomes `'01201'`)

**Comment by therealOri** [comment]
> How much RAM memory do you have? The code is not really optimized in terms of memory (or optimized in any terms at all), so after doing a quick run here on the word list of 3b1b, you might need around 10-12 gigs of memory.
> 
> 
> A (slight) fix from the top of my head: the dictionary representation could be done much more efficiently. Currently we use 5 integers for every possible combination (and there are `3**5` or `243` of them). So roughly `250*5` integers, let's say 4 bytes each, which means 5000 bytes per word. Just replacing those 5 integers by a string of 5 characters requires only 1250 bytes and cuts down memory usage by 4 (i.e. `(0, 1, 2, 0, 1)` becomes `'01201'`)


Ah, ok.

And I have 8GBs of RAM. So RIP lol.
