### ISSUE TITLE
`calculate_pattern` duplicate letter follow-up

### ISSUE THREAD

**Issue by gbotev1** [GillesVandewiele/Wordle-Bot#3]
I think you need to do two passes in order to also catch corner cases like `calculate_pattern('rower', 'goner')`, which currently returns `(1, 2, 0, 2, 2)` instead of `(0, 2, 0, 2, 2)`.

_Originally posted by @gbotev1 in https://github.com/GillesVandewiele/Wordle-Bot/issues/2#issuecomment-1038630546_

**Comment by GillesVandewiele** [comment]
Thank you for reporting this. Should be fixed with next push, and I credited you in the code.
